### PR TITLE
min amount per deposit

### PR DESCRIPTION
**Pull request by adam-hanna**
Please go the the `Preview` tab and select the appropriate sub-template:

Cherry picking from https://github.com/informalsystems/cosmos-sdk/tree/masa/backport-18146-min-amount-per-deposit (related [PR](https://github.com/cosmos/cosmos-sdk/pull/19312/files))

* [Production code](?expand=1&template=production.md) - for types `fix`, `feat`, and `refactor`.
* [Docs](?expand=1&template=docs.md) - for documentation changes.
* [Others](?expand=1&template=others.md) - for changes that do not affect production code.

### CODE REVIEW

**Comment by adam-hanna** [comment]
There are ALOT of linting issues, which I will slowly chip away at

**Comment by giunatale** [comment]
I think the entire Cosmos SDK codebase was merged here by mistake, while the idea was to cherry pick the x/gov modifications. A hint is the over 2000 files part of the PR most of which are additions. Just pointing it out fyi before it becomes even harder to revert without losing work done

**Comment by adam-hanna** [comment]
> I think the entire Cosmos SDK codebase was merged here by mistake, while the idea was to cherry pick the x/gov modifications. A hint is the over 2000 files part of the PR most of which are additions. Just pointing it out fyi before it becomes even harder to revert without losing work done.
> 
> Should also rebase onto main since we switched over having x/gov own types

This was the minimal import of the cosmos-sdk that it took to cherry pick that commit. I know it's hard to believe but I started with the commit and simply kept importing packages/modules until I could build

**Comment by giunatale** [comment]
> This was the minimal import of the cosmos-sdk that it took to cherry pick that commit. I know it's hard to believe but I started with the commit and simply kept importing packages/modules until I could build

If you look at the PR https://github.com/cosmos/cosmos-sdk/pull/19312/files this is what it touches 
image
and in reality the changes in proto for staking and the change in bank can be discarded, so the PR is focused on x/gov. I don't think you really have to merge the whole sdk into the atomone app. Only the x/gov forked module needs to be updated (and the e2e tests I believe)

**Pull request closed without merging**
