### PR TITLE
feat(x/gov): min amount per deposit

### PR DESCRIPTION
**Pull request by adam-hanna**
Please go the the `Preview` tab and select the appropriate sub-template:

* [Production code](?expand=1&template=production.md) - for types `fix`, `feat`, and `refactor`.
* [Docs](?expand=1&template=docs.md) - for documentation changes.
* [Others](?expand=1&template=others.md) - for changes that do not affect production code.

### CODE REVIEW

**Comment by adam-hanna** [comment]
Ok, the problem with my other PR, is that I tried to bring in every file that was changed by that PR.

Now that I have a better understanding of the cosmos-sdk code base, I know that some of the changes aren't relevant for what we're trying to do now.

This is a much smaller PR :)

**Review by tbruyelle — CHANGES_REQUESTED** [review]
Nice job! It looks pretty good now.
Just one tiny thing, it seems that you (accidentaly?) run gofumpt on the generated proto files. You can see that by re-generate them using `make proto-gen`, the new files are different where they shouldn't. Just fix that and we should be good to merge.

**Comment by adam-hanna** [comment]
> Nice job! It looks pretty good now. Just one tiny thing, it seems that you (accidentaly?) run gofumpt on the generated proto files. You can see that by re-generate them using `make proto-gen`, the new files are differents whereas they shouldn't. Just fix that and we should be good to merge.

Ok, I re-generated them. It seems like there are still some minor formatting differences? Could be because I'm on a diff version of buf?

```bash
$ buf --version
1.32.1
```

**Comment by tbruyelle** [comment]
> Ok, I re-generated them. It seems like there are still some minor formatting differences? Could be because I'm on a diff version of buf?

I don't see any differences, I pulled your changes and ran `make proto-gen`, no changes so all good.

**Review by tbruyelle — APPROVED** [review]

**Pull request merged**
